# NAME: Ruff configuration file for Python linting
# DESCRIPTION: This file is used to configure the Ruff linter for Python.
#   Ruff is a wrapper around multiple linters and formatters for Python.
#   It is used to enforce a consistent code style across a codebase.
#   This file is used to configure the linters and formatters that Ruff will use.
#   For more information: https://docs.astral.sh/ruff/
# SOURCE: Source of truth on this configuration is located here:
#   https://github.com/ansiblejunky/ansible-project-template/blob/master/.ruff.toml

[lint]
select = [
    "N", # pep8-naming
    "PL", # pylint
    "F", # pyflakes
    "B", # flake8-bugbear
    "G", # flake8-logging-format
    "BLE", # flake8-blind-except
    "C4", # flake8-comprehensions
    "T10", # flake8-debugger
    "Q", # flake8-quotes
    "SIM", # flake8-simplify
    "RET", # flake8-return
    "A", # flake8-builtins
    "ISC", # flake8-implicit-str-concat
    "ARG", # flake8-unused-arguments
    "SLF", # flake8-self
    "S", # flake8-bandit
    "PIE", # flake8-pie
    "COM", # flake8-commas
    "TID", # flake8-tidy-imports
    "E", # pycodestyle error
    "W", # pycodestyle warning
    "D", # pydocstyle
    "I", # isort
    "TRY", # tryceratops
    "C90", # mccabe
]
extend-select = [
    "UP", # pyupgrade
]
ignore = [
    "D203", # incorrect-blank-line-before-class duplicate of D2111
    "D212", # multi-line docstring summary should start at the first line duplicate of D213
]